[common]
# Whether to use ANSI color in output
color = true

# Enable debug logging, shows HTTP requests
debug = false

# Redirect debug log to the given file
debug_file = "/tmp/toot.log"

# Log request and response bodies in the debug log
verbose = false

# Do not write to output
quiet = false

[commands.post]
editor = "vim"
sensitive = true
visibility = "unlisted"
scheduled_in = "30 minutes"

[commands.tui]
media_viewer = "img"

# 1 (monochrome)
# 16 (default)
# 88
# 256
# 16777216 (24 bit)
color = 256


[tui.palette]
status_list_timestamp = ["dark green",""]
# status_detail_timestamp = ["dark green",""]
footer_status = ["dark magenta",""]
footer_status_bold = ["dark magenta,bold",""]
footer_message = ["yellow",""]
footer_message_error = ["dark red",""]
header = ["dark magenta",""]
header_bold = ["dark magenta,bold",""]
columns_divider = ["dark red",""]

# card_author = ["dark green",""]
# card_title = ["dark green",""]
editbox = ["dark red",""]
editbox_focused = ["dark red",""]
status_detail_account= ["dark red",""]
status_detail_bookmark= ["dark red",""]
status_detail_timestamp= ["dark green",""]
status_list_account = ["dark blue",""]
status_list_selected = ["yellow","black"]
hashtag = ["dark red",""]
shortcut_highlight = ["dark red",""]

# intro_smalltext= ["dark red",""]
# intro_bigtext= ["dark red",""]
# content_warning= ["dark red",""]
# poll_bar= ["dark red",""]

# button= ["dark red",""]
# button_focused= ["dark red",""]

# ('status_detail_account', 'dark green', ''),
# ('status_detail_bookmarked', 'light red', ''),
# ('status_detail_timestamp', 'light blue', ''),
# ('status_list_account', 'dark green', ''),
# ('status_list_selected', 'white,bold', 'dark green', 'bold,underline'),
# ('status_list_timestamp', 'light blue', ''),

# # Functional
# ('account', 'dark green', ''),
# ('hashtag', 'light cyan,bold', '', 'bold'),
# ('hashtag_followed', 'yellow,bold', '', 'bold'),
# ('link', ',italics', '', ',italics'),
# ('link_focused', ',italics', 'dark magenta', "underline,italics"),
# ('shortcut', 'light blue', ''),
# ('shortcut_highlight', 'white,bold', '', 'bold'),
# ('warning', 'light red', ''),

# # Visibility
# ('visibility_public', 'dark gray', ''),
# ('visibility_unlisted', 'white', ''),
# ('visibility_private', 'dark cyan', ''),
# ('visibility_direct', 'yellow', ''),


