mxid: ""
device_id: ""
access_token: ""
homeserver: ""
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
backspace1_removes_word: true
backspace2_removes_word: false
always_clear_screen: true
data_dir: /home/xaos/.local/share/gomuks
cache_dir: /home/xaos/.cache/gomuks
history_path: /home/xaos/.cache/gomuks/history.db
room_list_path: /home/xaos/.cache/gomuks/rooms.gob.gz
media_dir: /home/xaos/.cache/gomuks/media
download_dir: /home/xaos/
state_dir: /home/xaos/.cache/gomuks/state
